[build]
builder = "nixpacks"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "./start.sh"
healthcheckPath = "/api/stats"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[env]
# Python version
NIXPACKS_PYTHON_VERSION = "3.13"
# Disable bytecode caching for faster builds
PYTHONDONTWRITEBYTECODE = "1"
# Unbuffered output for better logging
PYTHONUNBUFFERED = "1"
